### ISSUE TITLE
Polyfill crashes because listener is undefined

### ISSUE THREAD

**Issue by TheProgrammingMaster** [ungap/event-target#4]
Hello!

I'm using this polyfill in ie11 and it crashes sometimes at this line: https://github.com/ungap/event-target/blob/master/index.js#L68

I get the error: "Unable to get property 'handleEvent' of undefined or null reference". When I check the info object, it's listener and options are undefined. Anyone has a clue of why? And what I can do to fix it?

**Comment by WebReflection** [comment]
don't add null/undefined listeners?

**Comment by TheProgrammingMaster** [comment]
Haha embarrassing, thanks for a quick answer! Have a good weekend!

**Comment by WebReflection** [comment]
FWIW, if standards ignore those without throwing, I might follow their pattern, but the [goal of these polyfills](https://ungap.github.io/#pragmaticisbetterthansubsupimsupsubperfect) is to avoid unnecessary bloat, and a guard against `null` or `undefined` listeners look like a code smell to me, not something this poly should be bloated for.

I hope you agree, as it looks like this polyfill helped you fixing a bug 😉

**Comment by TheProgrammingMaster** [comment]
Latest chrome/chromium/firefox doesn't crash so I guess the standard ignores undefined listeners. But I don't think you need to change this; there's no point in having undefined listeners so you helped us remove some unnecessary lines:)
