### ISSUE TITLE
Unable to extend EventTarget

### ISSUE THREAD

**Issue by alshdavid** [ungap/event-target#5]
Unable to extend `EventTarget` in NodeJS and Jest

```javascript
const EventTarget = require('@ungap/event-target')

class L extends EventTarget {}

const listener = new L();

const event = new CustomEvent('a');

listener.addEventListener('a', console.log);
listener.dispatchEvent(event);
```

**Comment by WebReflection** [comment]
there is no information regarding **where** it fails, or what you are using to transpile this module, or if it's running in nodejs ... all I can say is that it works for me, so you need to give me more details.

**Comment by horaklukas** [comment]
I've been troubled by extending `EventTarget` in Safari so I used the `@ungap/event-target` polyfill. Now it works in Safari but produces the error in Chrome 84

```
Uncaught TypeError: Failed to construct 'EventTarget': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
``` 

Maybe it's the same issue.

I'm building the app with rollup and using the polyfill as 

```
import EventTarget from '@ungap/event-target';
```

The weird about it is when I use the CDN served version, it works well in both browsers.

**Comment by alshdavid** [comment]
Updated to include that I was talking about nodejs and Jest

**Comment by WebReflection** [comment]
I think you all have tooling issues ... I've just done this:

```sh
mkdir test
cd test
npm init -y
npm i @ungap/event-target
```

then I've created this file `test.js`

```js
const EventTarget = require('@ungap/event-target')

class L extends EventTarget {}

const listener = new L();
```

then `node test.js`

no issue whatsoever, so I've no idea what you are doing, what your toolchain is doing, or how to help.

**Comment by WebReflection** [comment]
P.S. specifying `"type": "module"` and using this `test.js` file instead, works as well just fine.

```js
import EventTarget from '@ungap/event-target'

class L extends EventTarget {}

const listener = new L();
```

I think you should all file an issue in Jest, rollup, or whatever it is that is failing in your *non standard* Node.js or browser environment, but if you find the culprit and there's something I can do, please let me know.
